<#
.SYNOPSIS
  Installs opencode-goal-plugin by writing a one-line loader into the global
  OpenCode plugins directory.

.DESCRIPTION
  OpenCode discovers .ts files in ~/.config/opencode/plugins/ and loads them
  directly. A plugin *directory* inside that folder is not picked up, and a
  directory path in the `plugins` array of opencode.json(c) is ignored, so the
  reliable form is a single loader file that re-exports the plugin from here.

  The loader is one line. Move this folder and re-run this script; delete the
  loader to uninstall.

.PARAMETER Force
  Overwrite an existing loader file.
#>
[CmdletBinding()]
param([switch]$Force)

$ErrorActionPreference = "Stop"

$pluginRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$entry = Join-Path $pluginRoot "src\index.ts"

if (-not (Test-Path $entry)) {
  throw "Plugin entry not found: $entry"
}

$pluginsDir = Join-Path $env:USERPROFILE ".config\opencode\plugins"
$loader = Join-Path $pluginsDir "goal.ts"

New-Item -ItemType Directory -Force -Path $pluginsDir | Out-Null

if ((Test-Path $loader) -and -not $Force) {
  $current = Get-Content $loader -Raw
  if ($current -match [regex]::Escape($pluginRoot)) {
    Write-Host "Already installed and pointing at this folder:"
    Write-Host "  $loader"
    exit 0
  }
  Write-Host "Refusing to overwrite an existing loader:" -ForegroundColor Yellow
  Write-Host "  $loader"
  Write-Host "Re-run with -Force after checking its contents."
  exit 1
}

# Forward slashes keep the import specifier valid on every platform, and spaces
# in the path are fine inside a quoted specifier.
$specifier = ([Uri]$entry).AbsoluteUri
$content = "// Generated by opencode-goal-plugin/install.ps1 - edit freely.`n// Delete this file to uninstall the plugin.`nexport { default } from `"$specifier`"`n"

Set-Content -Path $loader -Value $content -Encoding utf8

Write-Host "Installed: $loader"
Write-Host "  -> $entry"
Write-Host ""
Write-Host "Run 'opencode reload' (or restart the TUI) to load it."
Write-Host "Then type /goal help in a session."
