#!/bin/sh
# Installs opencode-goal-plugin by writing a one-line loader into the global
# OpenCode plugins directory.
#
# Works on macOS, Linux, WSL, and Git Bash on Windows. The plugin itself has no
# platform-specific code and no runtime dependencies; only this step needed a
# per-shell script.
#
# Move this folder and re-run to repoint the loader. Delete the loader to
# uninstall. Pass -f to overwrite a loader that points somewhere else.
#
# NOTE: this form gives you the server half only. A bare loader file has no
# package.json beside it, so the host cannot resolve the ./tui entrypoint and the
# terminal UI does not load. For that, install the package instead:
#     npx opencode plugin add opencode-goal-plugin

set -eu

force=0
for arg in "$@"; do
  case "$arg" in
    -f | --force) force=1 ;;
    -h | --help)
      echo "usage: sh install.sh [-f]"
      exit 0
      ;;
    *)
      echo "unknown option: $arg" >&2
      exit 1
      ;;
  esac
done

# Resolve this script's directory without relying on GNU readlink -f.
script="$0"
while [ -L "$script" ]; do
  link=$(readlink "$script")
  case "$link" in
    /*) script="$link" ;;
    *) script="$(dirname "$script")/$link" ;;
  esac
done
plugin_root=$(CDPATH= cd -- "$(dirname -- "$script")" && pwd -P)

entry="$plugin_root/src/index.ts"
if [ ! -f "$entry" ]; then
  echo "Plugin entry not found: $entry" >&2
  exit 1
fi

# On Git Bash and MSYS, `pwd -P` reports /c/Users/... which is not a valid
# module specifier for the Windows process that actually runs the plugin.
# cygpath -m converts it to C:/Users/... On macOS and Linux there is no
# cygpath and the native path is already correct.
if command -v cygpath >/dev/null 2>&1; then
  entry_specifier=$(cygpath -m "$entry")
else
  entry_specifier="$entry"
fi

# Honour XDG_CONFIG_HOME when set, otherwise use the documented default.
if [ -n "${XDG_CONFIG_HOME:-}" ]; then
  config_home="$XDG_CONFIG_HOME"
else
  config_home="$HOME/.config"
fi

plugins_dir="$config_home/opencode/plugins"
loader="$plugins_dir/goal.ts"
mkdir -p "$plugins_dir"

if [ -f "$loader" ] && [ "$force" -eq 0 ]; then
  if grep -qF "$entry_specifier" "$loader" 2>/dev/null; then
    echo "Already installed and pointing at this folder:"
    echo "  $loader"
    exit 0
  fi
  echo "Refusing to overwrite an existing loader:" >&2
  echo "  $loader" >&2
  echo "Re-run with -f after checking its contents." >&2
  exit 1
fi

# A quoted absolute path is a valid ESM specifier, and spaces in the folder name
# are fine inside the quotes. No percent-encoding step, so nothing to get wrong.
cat >"$loader" <<EOF
// Generated by opencode-goal-plugin/install.sh - edit freely.
// Delete this file to uninstall the plugin.
export { default } from "$entry_specifier"
EOF

echo "Installed: $loader"
echo "  -> $entry_specifier"
echo ""
echo "Run 'opencode reload' (or restart the TUI) to load it."
echo "Then type /goal help in a session."
